Repository brain-tec/queue, pull requests merged in 2023-11, with the labels that each got.

#307 15.0 mig base import async
  .pre-commit-config.yaml
  base_import_async/__manifest__.py
  base_import_async/i18n/tr.po
  base_import_async/models/base_import_import.py
  base_import_async/models/queue_job.py
  base_import_async/static/src/xml/import.xml
  base_import_async/views/base_import_async.xml
  setup/base_import_async/setup.py
Labels: 15.0.project_pr_449

#308 Syncing from upstream OCA/queue (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  export_async_schedule/README.rst
  export_async_schedule/__manifest__.py
  export_async_schedule/i18n/export_async_schedule.pot
  export_async_schedule/i18n/fr.po
  export_async_schedule/static/description/index.html
  export_async_schedule/views/export_async_schedule_views.xml
  queue_job/i18n/de.po
  queue_job/i18n/queue_job.pot
  queue_job/i18n/ro.po
  queue_job/i18n/zh_CN.po
  queue_job_batch/README.rst
  queue_job_batch/__manifest__.py
  queue_job_batch/i18n/fr.po
  queue_job_batch/i18n/queue_job_batch.pot
  queue_job_batch/static/description/index.html
  queue_job_batch/views/queue_job_batch_views.xml
Labels: 14.0

#309 Syncing from upstream OCA/queue (16.0)
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 16.0

#310 Syncing from upstream OCA/queue (14.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/job.py
  queue_job/static/description/index.html
  queue_job/tests/common.py
  test_queue_job/__manifest__.py
  test_queue_job/tests/test_delay_mocks.py
Labels: 14.0

#311 Syncing from upstream OCA/queue (15.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/jobrunner/runner.py
  queue_job/static/description/index.html
Labels: 15.0

#312 Syncing from upstream OCA/queue (14.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/jobrunner/runner.py
  queue_job/static/description/index.html
Labels: 14.0

#313 Syncing from upstream OCA/queue (15.0)
  README.md
  base_export_async/README.rst
  base_export_async/__manifest__.py
  base_export_async/models/delay_export.py
  base_export_async/static/description/index.html
  base_export_async/tests/test_base_export_async.py
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/job.py
  queue_job/static/description/index.html
  queue_job/tests/common.py
  test_queue_job/__manifest__.py
  test_queue_job/tests/test_delay_mocks.py
Labels: 15.0

#314 Syncing from upstream OCA/queue (16.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/job.py
  queue_job/jobrunner/runner.py
  queue_job/static/description/index.html
  queue_job/tests/common.py
  test_queue_job/__manifest__.py
  test_queue_job/tests/test_delay_mocks.py
Labels: 16.0

#315 Syncing from upstream OCA/queue (15.0)
  queue_job/jobrunner/runner.py
Labels: 15.0

#316 Syncing from upstream OCA/queue (16.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/jobrunner/runner.py
  queue_job/static/description/index.html
Labels: 16.0

#317 Syncing from upstream OCA/queue (12.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/i18n/da.po
  queue_job/i18n/de.po
  queue_job/i18n/es.po
  queue_job/i18n/fr.po
  queue_job/i18n/pt.po
  queue_job/i18n/queue_job.pot
  queue_job/i18n/zh_CN.po
  queue_job/job.py
  queue_job/models/queue_job.py
  queue_job/static/description/index.html
  queue_job/tests/test_delayable.py
Labels: 12.0

#318 Syncing from upstream OCA/queue (14.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/job.py
  queue_job/static/description/index.html
Labels: 14.0

#319 Syncing from upstream OCA/queue (13.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/models/queue_job.py
  queue_job/static/description/index.html
Labels: 13.0

#321 Syncing from upstream OCA/queue (15.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/models/queue_job.py
  queue_job/static/description/index.html
Labels: 15.0

#323 Syncing from upstream OCA/queue (15.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/i18n/de.po
  queue_job/i18n/es.po
  queue_job/i18n/fr.po
  queue_job/i18n/queue_job.pot
  queue_job/i18n/ro.po
  queue_job/i18n/zh_CN.po
  queue_job/models/queue_job.py
  queue_job/static/description/index.html
Labels: 15.0

#324 Syncing from upstream OCA/queue (16.0)
  README.md
  queue_job_batch/README.rst
  queue_job_batch/__init__.py
  queue_job_batch/__manifest__.py
  queue_job_batch/data/queue_job_channel_data.xml
  queue_job_batch/data/queue_job_function_data.xml
  queue_job_batch/i18n/fr.po
  queue_job_batch/i18n/queue_job_batch.pot
  queue_job_batch/models/__init__.py
  queue_job_batch/models/queue_job.py
  queue_job_batch/models/queue_job_batch.py
  queue_job_batch/readme/CONTRIBUTORS.rst
  queue_job_batch/readme/CREDITS.rst
  queue_job_batch/readme/DESCRIPTION.rst
  queue_job_batch/readme/USAGE.rst
  queue_job_batch/security/ir.model.access.csv
  queue_job_batch/security/security.xml
  queue_job_batch/static/description/icon.png
  queue_job_batch/static/description/icon.svg
  queue_job_batch/static/description/index.html
  queue_job_batch/static/src/js/batch.esm.js
  queue_job_batch/static/src/js/batch_menu_container_view.esm.js
  queue_job_batch/static/src/js/batch_menu_model.esm.js
  queue_job_batch/static/src/js/batch_menu_view.esm.js
  queue_job_batch/static/src/js/ir_model.esm.js
  queue_job_batch/static/src/js/systray_service.esm.js
  queue_job_batch/static/src/scss/systray.scss
  queue_job_batch/static/src/xml/queue_job_batch_menu.xml
  queue_job_batch/static/src/xml/queue_job_batch_menu_controller.xml
  queue_job_batch/views/queue_job_batch_views.xml
  queue_job_batch/views/queue_job_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/queue_job_batch/odoo/addons/queue_job_batch
  setup/queue_job_batch/setup.py
  setup/test_queue_job_batch/odoo/addons/test_queue_job_batch
  setup/test_queue_job_batch/setup.py
  test_queue_job_batch/README.rst
  test_queue_job_batch/__init__.py
  test_queue_job_batch/__manifest__.py
  test_queue_job_batch/i18n/fr.po
  test_queue_job_batch/i18n/test_queue_job_batch.pot
  test_queue_job_batch/readme/CONTRIBUTORS.rst
  test_queue_job_batch/readme/CREDITS.rst
  test_queue_job_batch/readme/DESCRIPTION.rst
  test_queue_job_batch/static/description/icon.png
  test_queue_job_batch/static/description/icon.svg
  test_queue_job_batch/static/description/index.html
  test_queue_job_batch/tests/__init__.py
  test_queue_job_batch/tests/test_queue_job_batch.py
Labels: 16.0
