Repository brain-tec/queue, pull requests merged in 2023-03, with the labels that each got.

#251 Syncing from upstream OCA/queue (15.0)
  .oca/oca-port/blacklist/queue_job.json
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/controllers/main.py
  queue_job/fields.py
  queue_job/jobrunner/runner.py
  queue_job/models/base.py
  queue_job/models/queue_job.py
  queue_job/readme/USAGE.rst
  queue_job/static/description/index.html
  queue_job/tests/test_json_field.py
  test_queue_job/__manifest__.py
  test_queue_job/models/test_models.py
  test_queue_job/tests/test_json_field.py
Labels: 15.0

#252 Syncing from upstream OCA/queue (16.0)
  .oca/oca-port/blacklist/queue_job.json
  README.md
  queue_job/__manifest__.py
  queue_job/controllers/main.py
  queue_job/delay.py
  queue_job/jobrunner/runner.py
  queue_job/models/queue_job.py
Labels: 16.0

#253 Syncing from upstream OCA/queue (13.0)
  queue_job/i18n/es.po
Labels: 13.0

#254 Syncing from upstream OCA/queue (13.0)
  queue_job/i18n/es.po
Labels: 13.0

#255 Syncing from upstream OCA/queue (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: 14.0

#256 Syncing from upstream OCA/queue (15.0)
  .copier-answers.yml
Labels: 15.0

#257 Syncing from upstream OCA/queue (16.0)
  .copier-answers.yml
Labels: 16.0

#258 Syncing from upstream OCA/queue (12.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 12.0

#259 Syncing from upstream OCA/queue (13.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  requirements.txt
Labels: 13.0

#260 [MIG] base_import_async migration to v15
  .pre-commit-config.yaml
  base_import_async/__manifest__.py
  base_import_async/models/base_import_import.py
  base_import_async/models/queue_job.py
  base_import_async/static/src/xml/import.xml
  base_import_async/views/base_import_async.xml
  setup/base_import_async/odoo/addons/base_import_async
  setup/base_import_async/setup.py
Labels: 15.0.project_mi_465

#263 Syncing from upstream OCA/queue (14.0)
  README.md
  queue_job/__manifest__.py
  queue_job/models/queue_job.py
Labels: 14.0

#264 Syncing from upstream OCA/queue (15.0)
  README.md
  queue_job/__manifest__.py
  queue_job/models/queue_job.py
Labels: 15.0

#265 Syncing from upstream OCA/queue (16.0)
  README.md
  queue_job/__manifest__.py
  queue_job/models/queue_job.py
Labels: 16.0
