Repository brain-tec/queue, pull requests merged in 2025-03, with the labels that each got.

#454 Syncing from upstream OCA/queue (16.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/i18n/de.po
  queue_job/jobrunner/runner.py
  queue_job/static/description/index.html
Labels: 16.0

#455 Syncing from upstream OCA/queue (17.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/controllers/main.py
  queue_job/data/queue_data.xml
  queue_job/i18n/de.po
  queue_job/i18n/es.po
  queue_job/i18n/it.po
  queue_job/i18n/queue_job.pot
  queue_job/i18n/zh_CN.po
  queue_job/job.py
  queue_job/jobrunner/runner.py
  queue_job/migrations/17.0.1.2.0/pre-migration.py
  queue_job/models/__init__.py
  queue_job/models/queue_job.py
  queue_job/models/queue_job_lock.py
  queue_job/readme/CONFIGURE.md
  queue_job/security/ir.model.access.csv
  queue_job/static/description/index.html
  queue_job/tests/__init__.py
  queue_job/tests/test_requeue_dead_job.py
Labels: 17.0

#456 Syncing from upstream OCA/queue (17.0)
  queue_job/i18n/it.po
Labels: 17.0

#457 Syncing from upstream OCA/queue (14.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/jobrunner/runner.py
  queue_job/static/description/index.html
  queue_job/tests/test_runner_runner.py
Labels: 14.0

#458 Syncing from upstream OCA/queue (18.0)
  README.md
  queue_job/README.rst
  queue_job/__manifest__.py
  queue_job/static/description/index.html
  queue_job/tests/common.py
  test_queue_job/__manifest__.py
  test_queue_job/tests/test_delay_mocks.py
Labels: 18.0

#460 [t158610] Add module base_import_async version 18.0
  base_import_async/README.rst
  base_import_async/__init__.py
  base_import_async/__manifest__.py
  base_import_async/data/queue_job_function_data.xml
  base_import_async/i18n/base_import_async.pot
  base_import_async/i18n/es.po
  base_import_async/i18n/it.po
  base_import_async/i18n/tr.po
  base_import_async/models/__init__.py
  base_import_async/models/base_import_import.py
  base_import_async/models/queue_job.py
  base_import_async/pyproject.toml
  base_import_async/readme/CONTRIBUTORS.md
  base_import_async/readme/CREDITS.md
  base_import_async/readme/DESCRIPTION.md
  base_import_async/readme/HISTORY.md
  base_import_async/readme/ROADMAP.md
  base_import_async/readme/USAGE.md
  base_import_async/static/description/icon.png
  base_import_async/static/description/index.html
  base_import_async/static/src/js/import_model.esm.js
  base_import_async/static/src/xml/import_data_sidepanel.xml
  base_import_async/tests/__init__.py
  base_import_async/tests/test_base_import_import.py
Labels: 18.0.project_ca_772

#461 Syncing from upstream OCA/queue (17.0)
  README.md
  base_import_async/README.rst
  base_import_async/__init__.py
  base_import_async/__manifest__.py
  base_import_async/data/queue_job_function_data.xml
  base_import_async/i18n/base_import_async.pot
  base_import_async/i18n/es.po
  base_import_async/i18n/it.po
  base_import_async/i18n/tr.po
  base_import_async/models/__init__.py
  base_import_async/models/base_import_import.py
  base_import_async/models/queue_job.py
  base_import_async/pyproject.toml
  base_import_async/readme/CONTRIBUTORS.md
  base_import_async/readme/CREDITS.md
  base_import_async/readme/DESCRIPTION.md
  base_import_async/readme/HISTORY.md
  base_import_async/readme/ROADMAP.md
  base_import_async/readme/USAGE.md
  base_import_async/static/description/icon.png
  base_import_async/static/description/index.html
  base_import_async/static/src/js/import_model.esm.js
  base_import_async/static/src/xml/import_data_sidepanel.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0
